@startuml diagrama
class Persona
class Foco{
    - Bool encendido
    + Encender ()
    + Apagar ()
}

class Juego

Class Mapa

Class Jugador

Class Serpiente

Class Eslabon 

Class Frutas

Class coordenadas

Class Cabeza

Class  Colisionable


Persona o-- Foco
Juego "1" *-- "1" Jugador
Juego "1" *-- "1" Mapa

Jugador "1" o-- "1" Serpiente
Serpiente "1" *-- "1" Eslabon
Serpiente "1" o-- "1" Cabeza
Cabeza --|> Eslabon
Cabeza "1" o-- "1" Frutas
Eslabon --|> Colisionable

Pared --|> Colisionable
Mapa "1" *-- "4" Pared

Class Lienzo
Class Dibujo
Class Pintor

Lienzo "1" *-- "*" Dibujo
Pintor *-- Dibujo
Pintor o-- Lienzo

Eslabon --|> Dibujo
Fruta --|> Dibujo
Mapa --|> Dibujo

Juego o-- Pintor

@enduml